# get the data.frame on san francisco demographics
# note that this csv file was generated by the script gen_df.R
library(RCurl)
sf_demographics = getURL("https://raw.githubusercontent.com/arilamstein/acs-zcta-explorer/master/sf_demographics.csv")
sf_demographics = read.csv(textConnection(sf_demographics), colClasses=c("region"="character"))
nrow(sf_demographics) # 27
head(sf_demographics)

# generate a boxplot showing the ethnicity of each zip code tabulated area (zcta) in san francisco
boxplot(sf_demographics[, c("percent_white", "percent_black", "percent_asian", "percent_hispanic")],
        main="San Francisco Zip Code Demographics",
        ylab="Percent")

# generate zcta choropleths of each ethnicity
library(choroplethrZip)
sf_demographics$value = sf_demographics$percent_white
choro_white = zip_choropleth(sf_demographics, title="Percent White", legend="Percent", num_colors=1, county_zoom=6075)
choro_white

sf_demographics$value = sf_demographics$percent_black
choro_black = zip_choropleth(sf_demographics, title="Percent Black\nor African American", legend="Percent", num_colors=1, county_zoom=6075)
choro_black

sf_demographics$value = sf_demographics$percent_asian
choro_asian = zip_choropleth(sf_demographics, title="Percent Asian", legend="Percent", num_colors=1, county_zoom=6075)
choro_asian

sf_demographics$value = sf_demographics$percent_hispanic
choro_hispanic = zip_choropleth(sf_demographics, title="Percent Hispanic\nor Latino", legend="Percent", num_colors=1, county_zoom=6075)
choro_hispanic

# show all 4 maps in the same image
library(gridExtra)
grid.arrange(choro_white, choro_black, choro_asian, choro_hispanic,
             main="San Francisco Zip Code Tabulated Areas (ZCTAs)\n")

# income 
boxplot_income = boxplot(sf_demographics[,"per_capita_income"],
                         ylab="Per Capita Income",
                         main="Per Capita Income in San Francisco Zips")
boxplot_income

# show a continuous and quartile map on the same image
sf_demographics$value=sf_demographics$per_capita_income
choro_income_continuous = zip_choropleth(sf_demographics, title="Continuous Scale", legend="Dollars", num_colors=1, county_zoom=6075)
choro_income_quartile = zip_choropleth(sf_demographics, title="Quartiles", legend="Dollars", num_colors=4, county_zoom=6075)
grid.arrange(choro_income_continuous, choro_income_quartile,
             main="San Francisco ZCTA Per Capita Income\n",
             nrow=1, ncol=2)
